import Head from "next/head";
import { Inter } from "next/font/google";
import styled from "styled-components";
import Image from "next/image";
import Page1 from "./index/page.1";
import Page2 from "./index/page.2";
import Page3 from "./index/page.3";
import Page4 from "./index/page.4";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>메인 페이지</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page1 />
      <Page2 />
      <Page3 />
      <Page4 />
    </>
  );
}
