import Head from "next/head";
import { Inter } from "next/font/google";
import Page1 from "./main/page.1";
import Page2 from "./main/page.2";
import Page3 from "./main/page.3";
import Page4 from "./main/page.4";

const inter = Inter({ subsets: ["latin"] });

export default function MainPage() {
  return (
    <>
      <Head>
        <title>메인 페이지</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Page1 />
        <Page2 />
        <Page3 />
        <Page4 />
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  return {
    props: {},
  };
};
